### ISSUE TITLE
Proxying a single IP address, or an IP subnet?

### ISSUE THREAD

**Issue by SpencerDawkins** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#1]
There is a question whether "IP proxying" means proxying an IP subnet, as opposed to proxying a single IP address. 

This question was discussed on the MASQUE mailing list during the adoption call for this draft. @DavidSchinazi asked me to open a Github issue for it. 

The adoption call mail thread starts at https://mailarchive.ietf.org/arch/msg/masque/cpcXQVBjpMQLbHMGpyAJCucEg3A/. I believe the first e-mail to mention the question is Magnus's at https://mailarchive.ietf.org/arch/msg/masque/5k_IUw6-A8jQi3i_q1MOtZt5Hl8/.

**Comment by DavidSchinazi** [comment]
My thought is that we'll define a way to proxy IP packets, not addresses. However, during negotiation the new protocol will need the ability to negotiate addresses, similar to DHCP. The most common use case will most likely be one where the client connects and the proxy assigns it one address (along with configuring gateway, routes, DNS, etc.). However, I believe that we should support the use case where the client tells the server "I own this subnet", since QBONE uses that in production today.

**Comment by gloinul** [comment]
@DavidSchinazi I think we should dig more into what the implications are of proxying a subnet compared to an address that comes from a range provided by the MASQUE server. I think these differences are significant and have impact on what is required for safe general deployment of the protocol. 

So if one proxying a single IP address borrowed from the MASQUE server then;
 - Source Address validation is trivial, the MASQUE client's traffic will leave the MASQUE server with an address belonging to the MASQUE server so no risk of source address spoofing.
 - There are no routing considerations for the MASQUE server as the address use by the MASQUE server is not routed by the MASQUE server. 

For a sub-net proxying the above concerns looks significantly different.
 - The MASQUE server does not own the IP subnet range and thus needs additional mechanism to determine if the MASQUE client is an actual gateway for that subnet or is simply spoofing that subnet.
 - The MASQUE server need to inject routes for the subnet upstream of it self to ensure that there are a return routability path. Such operations have significant operational concerns. 

Thus, the security considerations and necessary security model for these operational concerns are very different from proxying individual IP address belonging to the MASQUE server. That is why I am arguing that this needs to be an extension in a separate document. 

I understand that in QBONE you have this functionality. But, this is a specific use case and deployment where you have considered how you in this specific model handle these cases. Thus the scope and the description necessary are different from single IP address proxying. For a standardized mechanism I hope you agree that these concerns needs to be raised and addressed through either limitations in applicability scope and/or solutions to the security threats of using the mechanism. 

Thus can we put the subnet functionality as an extension where these additional scope and security aspects can be handled differently rather than trying to have them both in the same document. I also expect differences in progress due to the review and feedback necessary to bring the subnet parts to IETF consensus.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.

**Comment by mirjak** [comment]
How was this issue addressed? I think this is one of the main points we need to discuss and probably more text in the document would be useful as well.

**Comment by DavidSchinazi** [comment]
This issue was solved by clarifying the fact that this protocol proxies IP packets, not addresses or subnets, and specifying that any route exchange is purely informational. If that didn't address your concern, I might have misunderstood the concern - in that case can you elaborate?

**Comment by mirjak** [comment]
I was mostly referring to @gloinul comments and thinking that we probably need to say more about address validation anyway. Yes the proxy doesn't need to trust but does it decide?
