### ISSUE TITLE
Requirement on proxying unmodified packets

### ISSUE THREAD

**Issue by mirjak** [ietf-wg-masque/draft-ietf-masque-ip-proxy-reqs#13]
The first requirement says:

"The protocol will establish Data Transports, which will be able to forward IP packets, in their unmodified entirety."

This reads like IP packet can only be forwarded unmodified. This seems too restrictive for a requirement, as it wouldn't even allow any kind of preconfigured compression. I'm not even sure if we need a requirement to have an option to forward unmodified. There I actually propose to just remove it for now.

Also as a side note, I find the term Data Transport not ideal. How about Forwarding Association? That term is a bit clumsy but would be clear at least for me. I guess it would be good to agree to a common terminology here.

**Comment by mirjak** [comment]
I should probably open a separate issue on terminology but I just realised that what I proposed as Forwarding Association, is probably what you call an IP session in the draft. So in the sentence above it should probably say IP session instead of Data Transport...?

Also you use IP proxying and IP session and IP proxying session so what interchangeable in the draft. I think it would helpful to be more clear about terminology.

**Comment by DavidSchinazi** [comment]
From my perspective, unmodified forwarding is a requirement, whereas any kind of transformation (such as compression) is a nice-to-have. Requiring unmodified forwarding and allowing transformation via extensions is a more robust design than requiring some kind of compression and leaving unmodified to future work - because if you have unmodified you can fall back to it when your compressor fails, whereas the other way around is not possible.

Please open a separate issue for terminology.

**Comment by mirjak** [comment]
I think which one should be the default depends on the use case. I guess we maybe want to have both.

However, why do you think that your compressor could fail? I guess it strongly depends on how you compress, however, a compressor should not fail more easily than the rest of the protocol.

**Comment by DavidSchinazi** [comment]
That depends on how you build your compressor, I've implemented compressors in the past that would compress specific packets because they were the most common and let the uncommon ones go uncompressed.

**Comment by DavidSchinazi** [comment]
We wrote text in [draft-ietf-masque-ip-proxy-reqs-01](https://tools.ietf.org/html/draft-ietf-masque-ip-proxy-reqs-01) that should address this issue.

**Comment by mirjak** [comment]
I think this discussion about if any kind of compression should be an extension or part of the core protocol is not concluded.

**Comment by sysrqb** [comment]
Following this topic being raised at the interim, I'd also like to explicitly call out the fact that proxying unmodified IP packets will allow IP stack fingerprinting of the client on the other side of the proxy.

Either:
  1. the client serializes necessary header fields and payload, and the proxy constructs a new IP packet
  2. or, the packet is transported unmodified and the proxy provides a layer of abstraction and twiddles some of the header bits (and maintains an internal mapping)
 
(1) seems more preferable from a client-security point of view, and a little easier on the proxy implementation. (2) is easier on the client implementation, but nearly impossible for the client to know if it's actually happening on the proxy. As such, (1) would be my recommendation.

Leaving this as an extension will mean IP proxying will almost always leak the client's operating system.

**Comment by DavidSchinazi** [comment]
Hi @sysrqb can you elaborate on this IP stack fingerprinting please? Do you have a reference for what algorithm the attacker would use to determine the IP stack based on fields observed in the IP header?

**Comment by achernya** [comment]
I am not aware of any OS/client fingerprinting that works on the IP headers. I am aware of this for the TCP stack, namely [p0f](https://lcamtuf.coredump.cx/p0f3/).

Fingerprinting resistance in this manner is not really possible with IP proxying. The proposed solution of (1) would still be vulnerable to this (if fingerprinting on IP headers was possible) since there could be enough entropy in the header fields (and extensions) used.

If fingerprinting resistance is desired, the target application should use CONNECT or CONNECT-UDP. In the case of CONNECT, the proxy server's OS would be providing the IP and TCP headers, so the fingerprint would detect the proxy rather than the client.

**Comment by sysrqb** [comment]
(Sorry, I began writing a response and then got pulled away)

@achernya mostly covered what I was going to say. In particular, my memory was a little fuzzy and I realize that, in retrospect, my wording was too strong regarding the OS fingerprintability using only IP packet headers. The only concerning field I know about is the initial TTL, and that generally partitions connections between "unix-like", "Windows", and "other".

When TCP is being encapsulated by an IPv4 packet, then some other signals may become available. A typical example is that the initial MSS is dependent on the OS. Different stacks may have other differing behavior that could be a signal, such as reprobing PMTU at different intervals.

My initial comment was a little rushed, and I agree that defending against this will be difficult (other than the proxy "adjusting" the packet's TTL). It is important that this risk is called out somewhere, even though this isn't a unique problem in masque. This requirements document may not be the best place for it, but the future IP proxying document should include it, at least.
